#!/usr/bin/fish
# vim:ft=fish
#    _
#   | |__  ___ _ ____      ___ __ ___  _ __ ___
#   | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#   | |_) \__ \ |_) \ V  V /| | | | | | | | (__
#   |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#             |_|                  by xeeny


for monitor in (xrandr | awk '/ connected / {print $1}')
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9 10 11 12
end

#bspc config top_padding 38

bspc config active_border_color             "#000000"
bspc config automatic_scheme                longest_side
bspc config border_width                    0
bspc config borderless_monocle              true
bspc config bottom_monocle_padding          0
bspc config bottom_padding                  0
bspc config center_pseudo_tiled             true
bspc config click_to_focus                  false
bspc config directional_focus_tightness     high
# bspc config external_rules_command
bspc config focus_follows_pointer           true
bspc config focused_border_color            "#FFFFFF"
bspc config gapless_monocle                 true
bspc config honor_size_hints                true
bspc config ignore_ewmh_focus               false
bspc config ignore_ewmh_fullscreen          none
bspc config ignore_ewmh_struts              false
bspc config initial_polarity                second_child
bspc config left_monocle_padding            0
bspc config left_padding                    0
bspc config mapping_events_count            0
bspc config merge_overlapping_monitors      false
bspc config normal_border_color             "#000000"
bspc config pointer_action1                 move
bspc config pointer_action2                 resize_side
bspc config pointer_action3                 resize_corner
bspc config pointer_follows_focus           false
bspc config pointer_follows_monitor         true
bspc config pointer_modifier                mod4
# bspc config pointer_motion_interval
bspc config presel_feedback                 true
bspc config presel_feedback_color           "#222222"
bspc config removal_adjustment              true
bspc config remove_disabled_monitors        false
bspc config remove_unplugged_monitors       false
bspc config right_monocle_padding           0
bspc config right_padding                   0
bspc config single_monocle                  false
bspc config split_ratio                     0.5
bspc config status_prefix                   W
bspc config swallow_first_click             false
bspc config top_monocle_padding             0
bspc config top_padding                     0
bspc config window_gap                      10
